### ISSUE TITLE
Beef not running : After All gem file the rubyracer

### ISSUE THREAD

**Issue by Tikam02** [beefproject/beef#1396]
root@kali:/usr/share/beef-xss# gem install therubyracer -v 0.12.
ERROR:  While executing gem ... (Gem::Requirement::BadRequirementError)
    Illformed requirement ["0.12."]

root@kali:/usr/share/beef-xss# gem install therubyracer -v 0.12.2
Fetching: therubyracer-0.12.2.gem (100%)
Building native extensions.  This could take a while...
Successfully installed therubyracer-0.12.2
Parsing documentation for therubyracer-0.12.2
Installing ri documentation for therubyracer-0.12.2
Done installing documentation for therubyracer after 0 seconds
1 gem installed

root@kali:/usr/share/beef-xss# bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will
break this application for all non-root users on this machine.
Warning: the running version of Bundler (1.13.6) is older than the version that created the lockfile (1.14.4). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Using public_suffix 2.0.5
Using ansi 1.5.0
Using chunky_png 1.3.8
Using daemons 1.2.4
Using json 1.8.6
Using json_pure 1.8.6
Using multi_json 1.12.1
Using eventmachine 1.0.9.1
Using http_parser.rb 0.6.0
Using erubis 2.7.0
Using espeak-ruby 1.0.4
Using execjs 2.7.0
Using fastercsv 1.5.5
Using filesize 0.1.1
Using geoip 1.6.3
Using rkelly-remix 0.0.7
Using libv8 3.16.14.19
Using metasm 1.0.3
Using mime-types-data 3.2016.0521
Using mini_portile2 2.1.0
Using mojo_magick 0.5.6
Using msgpack 1.1.0
Using rb-readline-r7 0.5.2.0
Using robots 0.10.1
Using parseconfig 1.0.8
Using rack 1.6.5
Using rainbow 2.2.1
Using ref 2.0.0
Using rubyzip 1.2.1
Using tilt 2.0.7
Using tins 1.13.2
Using bundler 1.13.6
Using addressable 2.5.1
Using rqrcode 0.10.1
Using em-websocket 0.5.1
Using uglifier 3.2.0
Using jsobfu 0.4.2
Using mime-types 3.1
Using nokogiri 1.7.1
Using rack-protection 1.5.3
Using thin 1.7.0
Using rexec 1.6.3
Using therubyracer 0.12.3
Using term-ansicolor 1.5.0
Using data_objects 0.10.17
Using dm-core 1.2.1
Using qr4r 0.4.1
Using rex 2.0.10
Using sinatra 1.4.8
Using rubydns 0.7.3
Using do_sqlite3 0.10.17
Using dm-do-adapter 1.2.0
Using dm-migrations 1.2.0
Using dm-serializer 1.2.2
Using msfrpc-client 1.1.0
Using dm-sqlite-adapter 1.2.0
Bundle complete! 26 Gemfile dependencies, 56 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

root@kali:/usr/share/beef-xss# ./beef
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'uglifier'. (Bundler::GemRequireError)
Gem Load Error is: wrong argument type Class (expected Module)
Backtrace for gem load error is:
/usr/lib/ruby/vendor_ruby/v8/conversion.rb:23:in `include'
/usr/lib/ruby/vendor_ruby/v8/conversion.rb:23:in `block (2 levels) in <top (required)>'
/usr/lib/ruby/vendor_ruby/v8/conversion.rb:22:in `class_eval'
/usr/lib/ruby/vendor_ruby/v8/conversion.rb:22:in `block in <top (required)>'
/usr/lib/ruby/vendor_ruby/v8/conversion.rb:21:in `each'
/usr/lib/ruby/vendor_ruby/v8/conversion.rb:21:in `<top (required)>'
/var/lib/gems/2.3.0/gems/therubyracer-0.12.3/lib/v8.rb:22:in `require'
/var/lib/gems/2.3.0/gems/therubyracer-0.12.3/lib/v8.rb:22:in `<top (required)>'
/var/lib/gems/2.3.0/gems/execjs-2.7.0/lib/execjs/ruby_racer_runtime.rb:108:in `require'
/var/lib/gems/2.3.0/gems/execjs-2.7.0/lib/execjs/ruby_racer_runtime.rb:108:in `available?'
/var/lib/gems/2.3.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:63:in `each'
/var/lib/gems/2.3.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:63:in `find'
/var/lib/gems/2.3.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:63:in `best_available'
/var/lib/gems/2.3.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:57:in `autodetect'
/var/lib/gems/2.3.0/gems/execjs-2.7.0/lib/execjs.rb:5:in `<module:ExecJS>'
/var/lib/gems/2.3.0/gems/execjs-2.7.0/lib/execjs.rb:4:in `<top (required)>'
/var/lib/gems/2.3.0/gems/uglifier-3.2.0/lib/uglifier.rb:5:in `require'
/var/lib/gems/2.3.0/gems/uglifier-3.2.0/lib/uglifier.rb:5:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:91:in `require'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:91:in `block (2 levels) in require'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:86:in `each'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:86:in `block in require'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:75:in `each'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:75:in `require'
/usr/lib/ruby/vendor_ruby/bundler.rb:106:in `require'
/usr/share/beef-xss/core/loader.rb:10:in `<top (required)>'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
./beef:25:in `<main>'
Bundler Error Backtrace:
	from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:90:in `block (2 levels) in require'
	from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:86:in `each'
	from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:86:in `block in require'
	from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:75:in `each'
	from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:75:in `require'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:106:in `require'
	from /usr/share/beef-xss/core/loader.rb:10:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./beef:25:in `<main>'

**Comment by ziflar** [comment]
@Tikam02 
deleted the therubyracer 0.12.3 folder from /var/lib/gems/2.3.0/gems
run again

apt-get update && apt-get upgrade && apt-get dist-upgrade
apt-get install nodejs
gem install bundler
gem update bundler
gem install rake
gem install rubocop
gem update --system
gem install therubyracer -v 0.12.2
bundle install

**Comment by bcoles** [comment]
This should now be fixed. I've force downgraded therubyracer requirement to 0.12.2.

Make sure you have nodejs installed `apt-get install nodejs`

Then: `bundle install`

**Comment by Astrades** [comment]
I have everything installed that you guys mentioned. I have followed every one of these steps/fixes and sadly, my problem persists :(
So, now, it says that I'm having trouble trying to load "uglifier" while it's installed fine. 
:/

**Comment by ziflar** [comment]
@Astrades what system are you runing?
post here your error file 
if you are using kali rolling 
try my script from [here](https://github.com/ziflar/beef-xss_fix)

**Comment by bcoles** [comment]
Please don't necromance old issues. Create a new one, and fill in the requested details, including operating system and version of Ruby.

**Comment by Astrades** [comment]
sorry about that, already done.
