### ISSUE TITLE
public_port setting not working, cannot use internet connection

### ISSUE THREAD

**Issue by kdlsw** [beefproject/beef#1569]
#### Environment

What version/revision of BeEF are you using?
0.4.7.0-alpha
On what version of Ruby?
2.3.6p384
On what browser?
Firefox
On what operating system?
Kali

#### Configuration

Are you using a non-default configuration?
public: "123.ngrok.io"      # public hostname/IP address
public_port: "80" # experimental

Have you enabled or disabled any BeEF extensions?
Nope

#### Summary

Please provide a summary of the issue.
I'm trying to connect to the Beef server from internet, I did setup ngrok for port forwarding, but the public port setting in the config.yaml file didn't work, when I run beef in a terminal, it shows
[14:18:21][+] running on network interface: 123.ngrok.io
[14:18:21]    |   Hook URL: http://123.ngrok.io:3000/hook.js
[14:18:21]    |_  UI URL:   http://123.ngrok.io:3000/ui/panel

http://123.ngrok.io:3000/ this goes to nowhere, the public server is listening on 80.

If I put http://123.ngrok.io:80/hook.js as the hook link, the victim actually can get the js, but the problem is, once hook.js is running, the browser is still sending all the packets to http://123.ngrok.io:3000.

I think if I change the `port` in the config.yaml to 80, it might set all default link to 80, but then I cannot host a http server simultaneously, and I cannot change ngrok server port to 3000.

Any suggestions please? Thank you.

**Comment by bcoles** [comment]
Perhaps this will help:

https://github.com/beefproject/beef/issues?utf8=%E2%9C%93&q=is%3Aissue+ngrok+

**Comment by kdlsw** [comment]
@bcoles Thank you for replying, I have done quite a few researches, and read the link you put, I think [this](https://github.com/beefproject/beef/issues/1507) one is similar to my problem. Beef is by default setting hook.js reverse connection port the same as LAN side listening port. But unfortunately, unlike that post, I couldn't force the tunnel to listen WAN and LAN on the same port (except 80).
I guess what I really want to know is, is there a way to make Beef to have different WAN (hook.js reverse connection port) and LAN ports? Isn't "public_port" option for that matter? It seems not working. Thanks

**Comment by bcoles** [comment]
I have never used ngrok and don't intend to any time soon, so can't offer specifics.

Your issue is most likely one of network routing. You need to understand [how ngrok works](https://ngrok.com/product).

BeEF binds to all interfaces by default. You literally need to do nothing to get BeEF to work over a WAN interface. If you can't get network access to the admin panel or hook then your network config is broken.

Once you've got your network routes working, you'll want to set `public` and `public_port` for convenience in `config.yaml` as per the [FAQ](https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat). This is purely for convenience and is not a requirement. One of the conveniences is printing the hook URL and panel URL to the console. This is for convenience, like automatically populating some module options which need a connect back. This is not a requirement to get network routes working. This is not a requirement to hook browsers. These do not change which interfaces BeEF listens on. They are strings used elsewhere for convenience.

You literally need to do nothing to the BeEF config to work over WAN.

**Comment by bcoles** [comment]
My bad, you probably will need to set `public` and `public_port` to hook browsers.

However, you won't need to set these to verify that your network configuration is correct. The admin panel and hook should be accessible via the WAN interface once you've configured ngrok correctly. Then simply set `public: your.public.ngrok.host` and `public_port: 80 # or whatever the public ngrok URL uses`

**Comment by bcoles** [comment]
Glad you got it working.

Strange that the console output does not reflect the `public_host` and `public_port`. The port variable is used for the console output, at least in the latest version. However, this console output could probably use some improving when a `public_host` and `public_port` are set.

I'll leave this issue open to resolve in the future.

**Comment by bcoles** [comment]
The issue with the console startup banners should now be fixed.

66cb048ed70bd5a270c1c40bd83e03e16c6537a7

**Comment by TheUndeadPriest** [comment]
@kdlsw Bro so your BeEf running on WAN now? Can you help me out as well I am still not sure with the technicalities. Help much appreciated
