### ISSUE TITLE
BeEF not running

### ISSUE THREAD

**Issue by gsmart2424** [beefproject/beef#2153]
[i] GeoIP database is missing
[i] Run geoipupdate to download / update Maxmind GeoIP database
[*] Please wait for the BeEF service to start.
[*]
[*] You might need to refresh your browser once it opens.
[*]
[*]  Web UI: http://127.0.0.1:3000/ui/panel
[*]    Hook: <script src="http://<IP>:3000/hook.js"></script>
[*] Example: <script src="http://127.0.0.1:3000/hook.js"></script>

● beef-xss.service - beef-xss
     Loaded: loaded (/lib/systemd/system/beef-xss.service; disabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Tue 2021-08-24 05:00:54 EDT; 3s ago
    Process: 16436 ExecStart=/usr/share/beef-xss/beef (code=exited, status=1/FAILURE)
   Main PID: 16436 (code=exited, status=1/FAILURE)
        CPU: 1.071s

Aug 24 05:00:54 gsmart beef[16436]: [ 5:00:54][*] Browser Exploitation Framework (BeEF) 0.5.0.0
Aug 24 05:00:54 gsmart beef[16436]: [ 5:00:54]    |   Twit: @beefproject
Aug 24 05:00:54 gsmart beef[16436]: [ 5:00:54]    |   Site: https://beefproject.com
Aug 24 05:00:54 gsmart beef[16436]: [ 5:00:54]    |   Blog: http://blog.beefproject.com
Aug 24 05:00:54 gsmart beef[16436]: [ 5:00:54]    |_  Wiki: https://github.com/beefproject/beef/wiki
Aug 24 05:00:54 gsmart beef[16436]: [ 5:00:54][*] Project Creator: Wade Alcorn (@WadeAlcorn)
Aug 24 05:00:54 gsmart beef[16436]: -- migration_context()
Aug 24 05:00:54 gsmart systemd[1]: beef-xss.service: Main process exited, code=exited, status=1/FAILURE
Aug 24 05:00:54 gsmart systemd[1]: beef-xss.service: Failed with result 'exit-code'.
Aug 24 05:00:54 gsmart systemd[1]: beef-xss.service: Consumed 1.071s CPU time.

[*] Opening Web UI (http://127.0.0.1:3000/ui/panel) in: 5... 4... 3... 2... 1...

**Comment by bcoles** [comment]
Browse to `http://127.0.0.1:3000/ui/panel`.

Check the logs with `journalctl -u beef-xss`.

**Comment by gsmart2424** [comment]
Thank you, i get it done

**Comment by wheatley** [comment]
hey @gsmart2424 was wondering if you were having any further issues

**Comment by subbusecurity** [comment]
I am facing the same issue, Details are below,

`
┌──(root💀kali)-[/usr/share/beef-xss]
└─# beef-xss     
[i] GeoIP database is missing
[i] Run geoipupdate to download / update Maxmind GeoIP database
[*] Please wait for the BeEF service to start.
[*]
[*] You might need to refresh your browser once it opens.
[*]
[*]  Web UI: http://127.0.0.1:3000/ui/panel
[*]    Hook: <script src="http://<IP>:3000/hook.js"></script>
[*] Example: <script src="http://127.0.0.1:3000/hook.js"></script>

● beef-xss.service - beef-xss
     Loaded: loaded (/lib/systemd/system/beef-xss.service; disabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Mon 2021-09-20 13:18:55 EDT; 3s ago
    Process: 62623 ExecStart=/usr/share/beef-xss/beef (code=exited, status=1/FAILURE)
   Main PID: 62623 (code=exited, status=1/FAILURE)
        CPU: 1.959s

Sep 20 13:18:55 kali beef[62623]: [13:18:54][*] Browser Exploitation Framework (BeEF) 0.5.0.0
Sep 20 13:18:55 kali beef[62623]: [13:18:54]    |   Twit: @beefproject
Sep 20 13:18:55 kali beef[62623]: [13:18:54]    |   Site: https://beefproject.com
Sep 20 13:18:55 kali beef[62623]: [13:18:54]    |   Blog: http://blog.beefproject.com
Sep 20 13:18:55 kali beef[62623]: [13:18:54]    |_  Wiki: https://github.com/beefproject/beef/wiki
Sep 20 13:18:55 kali beef[62623]: [13:18:54][*] Project Creator: Wade Alcorn (@WadeAlcorn)
Sep 20 13:18:55 kali beef[62623]: -- migration_context()
Sep 20 13:18:55 kali systemd[1]: beef-xss.service: Main process exited, code=exited, status=1/FAILURE
Sep 20 13:18:55 kali systemd[1]: beef-xss.service: Failed with result 'exit-code'.
Sep 20 13:18:55 kali systemd[1]: beef-xss.service: Consumed 1.959s CPU time.

[*] Opening Web UI (http://127.0.0.1:3000/ui/panel) in: 5... 4... 3... 2... 1... 
                                                                                                                                                                        
┌──(root💀kali)-[/usr/share/beef-xss]
└─# nano config.yaml                     
                                                                                                                                                                        
┌──(root💀kali)-[/usr/share/beef-xss]
└─# beef-xss        
[i] GeoIP database is missing
[i] Run geoipupdate to download / update Maxmind GeoIP database
[*] Please wait for the BeEF service to start.
[*]
[*] You might need to refresh your browser once it opens.
[*]
[*]  Web UI: http://127.0.0.1:3000/ui/panel
[*]    Hook: <script src="http://<IP>:3000/hook.js"></script>
[*] Example: <script src="http://127.0.0.1:3000/hook.js"></script>

● beef-xss.service - beef-xss
     Loaded: loaded (/lib/systemd/system/beef-xss.service; disabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Mon 2021-09-20 13:21:19 EDT; 1s ago
    Process: 62919 ExecStart=/usr/share/beef-xss/beef (code=exited, status=1/FAILURE)
   Main PID: 62919 (code=exited, status=1/FAILURE)
        CPU: 2.017s

Sep 20 13:21:19 kali beef[62919]: [13:21:19][*] Browser Exploitation Framework (BeEF) 0.5.0.0
Sep 20 13:21:19 kali beef[62919]: [13:21:19]    |   Twit: @beefproject
Sep 20 13:21:19 kali beef[62919]: [13:21:19]    |   Site: https://beefproject.com
Sep 20 13:21:19 kali beef[62919]: [13:21:19]    |   Blog: http://blog.beefproject.com
Sep 20 13:21:19 kali beef[62919]: [13:21:19]    |_  Wiki: https://github.com/beefproject/beef/wiki
Sep 20 13:21:19 kali beef[62919]: [13:21:19][*] Project Creator: Wade Alcorn (@WadeAlcorn)
Sep 20 13:21:19 kali beef[62919]: -- migration_context()
Sep 20 13:21:19 kali systemd[1]: beef-xss.service: Main process exited, code=exited, status=1/FAILURE
Sep 20 13:21:19 kali systemd[1]: beef-xss.service: Failed with result 'exit-code'.
Sep 20 13:21:19 kali systemd[1]: beef-xss.service: Consumed 2.017s CPU time.

[*] Opening Web UI (http://127.0.0.1:3000/ui/panel) in: 5... 4... 3... 2... 1... 
                                                                                                                                                                        
┌──(root💀kali)-[/usr/share/beef-xss]
└─# journalctl -u beef-xss
-- Journal begins at Sun 2021-05-30 18:21:15 EDT, ends at Mon 2021-09-20 13:21:48 EDT. --
Sep 15 13:22:05 kali systemd[1]: Started beef-xss.
Sep 15 13:22:08 kali beef[15803]: /var/lib/gems/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_con>
Sep 15 13:22:08 kali beef[15803]:         from /var/lib/gems/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/connection_handling.rb:327:in `retrieve_connection'
Sep 15 13:22:08 kali beef[15803]:         from /var/lib/gems/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/connection_handling.rb:283:in `connection'
Sep 15 13:22:08 kali beef[15803]:         from /var/lib/gems/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/migration.rb:912:in `connection'
Sep 15 13:22:08 kali beef[15803]:         from /var/lib/gems/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/migration.rb:919:in `block in method_missing'
Sep 15 13:22:08 kali beef[15803]:         from /var/lib/gems/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/migration.rb:897:in `block in say_with_time'
Sep 15 13:22:08 kali beef[15803]:         from /usr/lib/ruby/2.7.0/benchmark.rb:293:in `measure'
Sep 15 13:22:08 kali beef[15803]:         from /var/lib/gems/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/migration.rb:897:in `say_with_time'
Sep 15 13:22:08 kali beef[15803]:         from /var/lib/gems/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/migration.rb:918:in `method_missing'
Sep 15 13:22:08 kali beef[15803]:         from /usr/share/beef-xss/beef:171:in `<main>'
Sep 15 13:22:08 kali beef[15803]: [13:22:07][*] Browser Exploitation Framework (BeEF) 0.5.0.0
Sep 15 13:22:08 kali beef[15803]: [13:22:07]    |   Twit: @beefproject
Sep 15 13:22:08 kali beef[15803]: [13:22:07]    |   Site: https://beefproject.com
Sep 15 13:22:08 kali beef[15803]: [13:22:07]    |   Blog: http://blog.beefproject.com
Sep 15 13:22:08 kali beef[15803]: [13:22:07]    |_  Wiki: https://github.com/beefproject/beef/wiki
Sep 15 13:22:08 kali beef[15803]: [13:22:07][*] Project Creator: Wade Alcorn (@WadeAlcorn)
Sep 15 13:22:08 kali beef[15803]: -- migration_context()
Sep 15 13:22:08 kali systemd[1]: beef-xss.service: Main process exited, code=exited, status=1/FAILURE
Sep 15 13:22:08 kali systemd[1]: beef-xss.service: Failed with result 'exit-code'.
Sep 15 13:22:08 kali systemd[1]: beef-xss.service: Consumed 2.150s CPU time.
Sep 15 13:26:54 kali systemd[1]: Started beef-xss.
Sep 15 13:26:57 kali beef[16261]: /var/lib/gems/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_con>
Sep 15 13:26:57 kali beef[16261]:         from /var/lib/gems/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/connection_handling.rb:327:in `retrieve_connection'
Sep 15 13:26:57 kali beef[16261]:         from /var/lib/gems/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/connection_handling.rb:283:in `connection'
Sep 15 13:26:57 kali beef[16261]:         from /var/lib/gems/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/migration.rb:912:in `connection'
Sep 15 13:26:57 kali beef[16261]:         from /var/lib/gems/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/migration.rb:919:in `block in method_missing'
Sep 15 13:26:57 kali beef[16261]:         from /var/lib/gems/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/migration.rb:897:in `block in say_with_time'
Sep 15 13:26:57 kali beef[16261]:         from /usr/lib/ruby/2.7.0/benchmark.rb:293:in `measure'
Sep 15 13:26:57 kali beef[16261]:         from /var/lib/gems/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/migration.rb:897:in `say_with_time'
Sep 15 13:26:57 kali beef[16261]:         from /var/lib/gems/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/migration.rb:918:in `method_missing'
`

Any help is much appreciated.

**Comment by bcoles** [comment]
> I am facing the same issue, Details are below,

This is unrelated to the original issue. This also should have been fixed ages ago. Is your `beef-xss` package up to date?

**Comment by subbusecurity** [comment]
> > I am facing the same issue, Details are below,
> 
> This is unrelated to the original issue. This also should have been fixed ages ago. Is your `beef-xss` package up to date?

It is. I am using Kali 2021. And this problem persist even after apt-get update as well.

**Comment by bcoles** [comment]
> 
> 
> > > I am facing the same issue, Details are below,
> > 
> > 
> > This is unrelated to the original issue. This also should have been fixed ages ago. Is your `beef-xss` package up to date?
> 
> It is. I am using Kali 2021. And this problem persist even after apt-get update as well.

It looks like the Kali package is fairly old and needs to be updated (by the Kali package maintainers).

In the interim, you could try cloning BeEF from GitHub master branch or using one of the recent [releases](https://github.com/beefproject/beef/releases).

**Comment by subbusecurity** [comment]
Thanks, Great it works.
I need to do bundle install after this to fillin the missing gems.

I am delivering training on Penetration Testing. and I need beef badly.
Thanks for your timely help.

Regards
Subbu

**Comment by wheatley** [comment]
hey @subbusecurity, yes you'll need to do a bundle install after the clone.
if you receive any issues please let us know as you may face some dependancy issues.

**Comment by R4718** [comment]
how to fix method missing
